// react-app/ERPS/src/Components/Navbar/Navbar.jsx
import './Navbar.css';

function Navbar() {
    return (
        <nav className="navbar-overlay">
            <div className="container-fluid navtag">
                <a className="navbar-brand" href="#">
                    <img className="logo" src="/Logo.png" alt="Logo" />
                </a>
                <button className="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span className="navbar-toggler-icon"></span>
                </button>
                <div className="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul className="navbar-nav me-auto mb-2 mb-lg-0">
                        <li className="nav-item">
                            <a className="nav-link" aria-current="page" href="#">HOME</a>
                        </li>
                        <li className="nav-item">
                            <a className="nav-link" href="#">ABOUT US</a>
                        </li>
                    </ul>
                    <a href="">
                        <span className="material-symbols-outlined">
                            account_circle
                        </span>
                    </a>
                </div>
            </div>
        </nav>
    );
}

export default Navbar;

// angular-app/ERPS/src/app/navbar/navbar.component.ts
import { Component, HostListener } from '@angular/core';

@Component({
  selector: 'app-navbar',
  standalone: true,
  imports: [],
  templateUrl: './navbar.component.html',
  styleUrl: './navbar.component.css'
})
export class NavbarComponent {
  
  constructor() {} // empty means no initialization is required when an instance of this component is created

  // built in function for any initialization logic. called when the component is initialized
  ngOnInit(): void {
    if (typeof document !== 'undefined') {
      this.onWindowScroll();
    }
  }

  // Decorator that listens to the host for given event
  @HostListener('window:scroll', [])
  onWindowScroll(): void {
    if (typeof document !== 'undefined') { // Ensures that the code is runnning in the browser and not the server
      const navbar = document.querySelector('.navbar');
      if (window.scrollY > 50) { // If scrolled more than 50px, the scrolled class is added to navbar
        navbar?.classList.add('scrolled'); // The ? is to check if navbar is null or undefined. If not, it executes
      } else {
        navbar?.classList.remove('scrolled');
      }
    }
  }
}


<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid navtag">
    <a class="navbar-brand items" href="#">
      <img class="logo" src="/Logo.png" alt="Logo">
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link items" aria-current="page" href="#">HOME</a>
        </li>
        <li class="nav-item">
          <a class="nav-link items" href="#">ABOUT US</a>
        </li>
      </ul>
      <a href="">
        <span class="material-symbols-outlined">
        account_circle
        </span>
      </a>
    </div>
  </div>
</nav>
